config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_decisions, only: [:index, :new, :create]

  root to: "home#index"

  get "about/index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_decision.rb
# frozen_string_literal: true

class UserDecision < ApplicationRecord
  validates :age, presence: true
  validates :gender, presence: true
  validates :educational_level, presence: true
  validates :martial_status, presence: true
  validates :professional_area, presence: true
  validates :family_size, presence: true
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/user_decisions_controller.rb
# frozen_string_literal: true

class UserDecisionsController < ApplicationController
  def index
    @user_decisions = UserDecision.all
  end

  def new
    @user_decision = UserDecision.new
  end

  def create
    @user_decision = UserDecision.new(user_decision_params)
    @user_decision.decision = DecisionTree::ModelTraining.call(customer_attributes)

    if @user_decision.save
      redirect_to user_decisions_path,
                  notice: "This customer should probably buy products related to: #{@user_decision.decision}"
    else
      render :new
    end
  end

  private

  # formatting the params in an array of hashes to be used by the DecisionTree::ModelTraining service
  # this is the syntax expected by the DecisionTree::ModelTraining service to be able to be used
  def customer_attributes
    [
      user_decision_params[:gender], user_decision_params[:age], user_decision_params[:educational_level].to_s,
      user_decision_params[:martial_status].to_s, user_decision_params[:professional_area].to_s,
      user_decision_params[:family_size].to_s
    ]
  end

  def user_decision_params
    params.require(:user_decision).permit(:gender, :age, :educational_level, :martial_status, :professional_area,
                                          :family_size)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/about/index.html.haml
.container.col-xxl-8.px-4.py-4
  .row.flex-lg-row-reverse.align-items-center.g-4.py-4
    .col-lg-6
      %h1.display-5.fw-bold.lh-1.mb-3 About this project
      %br
      %p.lead The goal of this project is to apply a Decision Tree and train it with a dataset of customers, in order to predict what kind of product certain customer would buy.
      .d-grid.gap-2.d-md-flex.justify-content-md-start
    .col-lg-6
      = image_tag "binary-image.svg", class: " d-block mx-lg-auto img-fluid"

app/views/home/index.html.haml
.container.col-xxl-8.px-4.py-4
  .row.flex-lg-row-reverse.align-items-center.g-4.py-4
    .col-lg-6
      = image_tag "data-image.svg", class: " d-block mx-lg-auto img-fluid"
    .col-lg-6
      %h1.display-5.fw-bold.lh-1.mb-3 Decision Mate
      %p.lead A very smart algorithm that can predict what kind of product a customer could buy based on their caracteristics.
      .d-grid.gap-2.d-md-flex.justify-content-md-start
        = link_to "Try it now", new_user_decision_path, class: "btn btn-primary btn-lg px-4 me-md-2"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Decision Mate
    %meta(content = "width=device-width,initial-scale=1" name = "viewport")
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag "icon.ico"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "main", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  %body.d-flex.flex-column.min-vh-100
    %header
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.rounded
        .container-fluid
          %button.navbar-toggler(aria-controls = "navbarsExample10" aria-expanded = "false" aria-label = "Toggle navigation" data-bs-target = "#navbarsExample10" data-bs-toggle = "collapse" type = "button")
            %span.navbar-toggler-icon
          #navbarsExample10.collapse.navbar-collapse.justify-content-md-center
            %ul.navbar-nav
              %li.nav-item
                = link_to image_tag("app-logo.svg"), root_path, class: "navbar-brand"
              %li.nav-item
                = link_to "The Decision Mate", new_user_decision_path, class: "nav-link"
              %li.nav-item
                = link_to "Last Predictions", user_decisions_path, class: "nav-link"
              %li.nav-item
                = link_to "About the project", about_index_path, class: "nav-link"

    = yield

app/views/products/index.html.haml
%turbo-frame#main_content
  .container.col-xxl-8.px-4.py-4
    .row.flex-lg-row-reverse.align-items-center.g-4.py-4
      .col-lg-6(data-aos = "zoom-in" data-aos-duration="1500" data-aos-once="true")
        = image_tag "presentation-image.svg", class: " d-block mx-lg-auto img-fluid"
      .col-lg-6.red-background(data-aos = "zoom-in" data-aos-duration="1500" data-aos-once="true")
        %h1.display-5.fw-bold.lh-1.mb-3 Choose the product you would like to check:
        %select.form-select.form-select-lg.mb-3
          %option(selected = "selected") Select the product:
          %option(value = "1") Shoes
          %option(value = "2") Computer
          %option(value = "3") Video-game
          %option(value = "4") Mobile Phone
          %option(value = "5") Watch
        %button.btn.btn-primary(type = "submit") Next step

app/views/user_decisions/_form.html.haml
= form_for @user_decision do |f|
  - if @user_decision.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_decision.errors.count, "error")} prohibited this decision to be made:"
      %ul
        - @user_decision.errors.full_messages.each do |message|
          %li= message

  .field
    = f.select :gender, [["Male", "Male"], ["Female", "Female"], ["Other", "Other"]],
                        { include_blank: "Gender:" }, { class: "form-select form-select-md mb-3", required: "true" }
  .field
    = f.select :age, [["Baby", "Baby"], ["Kid", "Kid"], ["Teen", "Teen"], ["Young Adult", "Young Adult"],
                      ["Adult", "Adult"], ["Elder", "Elder"]],
                     { include_blank: "Age:" }, { class: "form-select form-select-md mb-3", required: "true" }
  .field
    = f.select :educational_level, [["Basic", "Basic"], ["Median", "Median"], ["Advanced", "Advanced"],
                                    ["Very Advanced", "Very Advanced"]],
                                   { include_blank: "Educational Level:" }, { class: "form-select form-select-md mb-3", required: "true" }
  .field
    = f.select :martial_status, [["Single", "Single"], ["Married", "Married"], ["Engaged", "Engaged"],
                                ["Divorced", "Divorced"], ["Other", "Other"]],
                                { include_blank: "Martial Status: " }, { class: "form-select form-select-md mb-3", required: "true" }
  .field
    = f.select :professional_area, [["Architecture and engineering", "Architecture and engineering"], ["Arts, culture and entertainment", "Arts, culture and entertainment"],
                                    ["Business, management and administration", "Business, management and administration"],
                                    ["Communications", "Communications"],
                                    ["Community and social services", "Community and social services"], ["Education", "Education"],
                                    ["Science and technology", "Science and technology"], ["Other", "Other"]],
                                   { include_blank: "Professional Area: " }, { class: "form-select form-select-md mb-3", required: "true" }
  .field
    = f.select :family_size, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5+", "> 5"]],
                             { include_blank: "Family Size: " }, { class: "form-select form-select-md mb-3", required: "true" }
  %br
  .center.text-center
    = f.submit "Discover the product this customer would buy", class: "btn btn-primary submit-button"

app/views/user_decisions/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @user_decision

= link_to 'Back', user_decisions_path

app/views/user_decisions/index.html.haml
.text-center
  %br
  %h2#notice= notice
  %br

%h4.text-center Last customer predictions
%br
.container
  %table.table.table-dark.table-striped.table-hover.table-bordered.table-responsive.table-sm.text-center
    %thead
      %tr
        %th(scope = "col") Gender:
        %th(scope = "col") Age:
        %th(scope = "col") Educational level:
        %th(scope = "col") Martial status:
        %th(scope = "col") Family size:
        %th(scope = "col") Professional area:
        %th(scope = "col") Customer Product Prediction:

    %tbody
      - @user_decisions.each do |user_decision|
        %tr
          %td= user_decision.gender
          %td= user_decision.age
          %td= user_decision.educational_level
          %td= user_decision.martial_status
          %td= user_decision.family_size
          %td= user_decision.professional_area
          %td= user_decision.decision
  %br
  .center
    = link_to 'New customer prediction', new_user_decision_path, class: "btn btn-primary btn-lg px-4 me-md-2"

app/views/user_decisions/new.html.haml
.container.col-xxl-8.px-4.py-4
  .row.flex-lg-row-reverse.align-items-center.g-4.py-4
    .col-lg-6
      = image_tag "presentation-image.svg", class: " d-block mx-lg-auto img-fluid"
    .col-lg-6
      %p.display-5.fw-bold.lh-1.mb-3 Choose the customer attributes to check the results:

      = render "form"

app/views/user_decisions/show.html.haml
%p#notice= notice

%p
  %b Gender:
  = @user_decision.gender
%p
  %b Age:
  = @user_decision.age
%p
  %b Educational level:
  = @user_decision.educational_level
%p
  %b Martial status:
  = @user_decision.martial_status
%p
  %b Professional area:
  = @user_decision.professional_area
%p
  %b Family size:
  = @user_decision.family_size

= link_to 'Edit', edit_user_decision_path(@user_decision)
\|
= link_to 'Back', user_decisions_path